create api endpoints + home page
uclouvain/osis-registration pull request #2
Opened 2021-05-27 13:17 UTC by mathieuzen

2021-06-07 11:17 UTC, albrugnetti requested changes
Est-ce que les statics de restframework sont utiles?

2021-07-12 07:46 UTC, mathieuzen commented on osis_registration/static/js/spinner.js
> +});
je l'enlève pour le moment mais on pourrait en avoir besoin si on incorpore de l'ajax dans les formulaires d'inscription

2021-07-12 13:39 UTC, albrugnetti reviewed
@mathieuzen  au niveau **layout.html** etc... Il faut supprimer ce dont nous n'avons plus besoin, je sais pas si tu comptes adapter/supprimer au fur et à mesure du dev?

2021-07-12 13:39 UTC, albrugnetti commented on osis_registration/templates/layout.html
> +{% endif %}
On peut supprimer (Utilisé dans le cadre des notifications OSIS - maintenance)

2021-07-12 13:39 UTC, albrugnetti commented on osis_registration/templates/layout.html
> +    {% endif %}
Idem

2021-07-12 13:46 UTC, albrugnetti approved these changes

2021-07-12 13:48 UTC, merged